### ISSUE TITLE
Error While Converting the Document when including a date taken from an attribute 

### ISSUE THREAD

**Issue by karmeye** [manuth/MarkdownConverter#174]
Hello @manuth 

When I try this example from the ReadMe file:

```
---
Date: 01-08-1291
---
Date taken from an attribute: {{ Date "dddd" }}
```

The generated pdf says:

> An Error Occurred While Converting the Document
> TypeError: (lookupProperty(...) || (depth0 && lookupProperty(...)) || container.hooks.helperMissing).call is not a function

Predefined dates work.

**Comment by manuth** [comment]
Hello @karmeye 
Sorry for letting you wait for such a long time.

Turns out that my `README.md` contains invalid code. I'm terribly sorry about that.

For `yaml` to detect your date values correctly, dates have to apply to the [ISO-8601](https://www.iso.org/iso-8601-date-and-time-format.html) standard as described on this website:
<https://symfony.com/doc/current/components/yaml/yaml_format.html#dates>

So the date should actually look like this:
```
---
Date: 1291-08-01
---
Date taken from an attribute: {{ Date "dddd" }}
```

I will make sure to change the README accordingly in the next version.
Until then, please make sure to keep this issue open so I can keep track of it.

Thanks for using Markdown Converter 😄
