### ISSUE TITLE
API support? 

### ISSUE THREAD

**Issue by yuis-ice** [manuth/MarkdownConverter#182]
Hi. I'd like to know if you have an API that parses a markdown content/file into a tokenized object, so we can use it as an API for our further vscode extension development. Thanks.

**Comment by manuth** [comment]
You might want to use the approach described in vscode doc's [Adding support for new syntax with markdown-it plugins](https://code.visualstudio.com/api/extension-guides/markdown-extension#adding-support-for-new-syntax-with-markdownit-plugins) chapter. This allows you to get VSCode's `markdown-it` parser which is able to do what you're looking for.

However - in order to have the `extendMarkdownIt`-method called, the Markdown Preview has do be opened at least once.
MarkdownConverter solves this by opening and closing a Markdown Preview if `extendMarkdownIt` hasn't been called so far.
https://github.com/manuth/MarkdownConverter/blob/2aa12a86c3863851da27676a9d14a6da32852cd2/src/System/Extensibility/Extension.ts#L132-L150

Hope this will help you. Please me know whether this helped or whether you have any further questions.

**Comment by yuis-ice** [comment]
Thanks. However I haven't fully understood. I understand that VSCode uses markdown-it, and we can extend its use() option by `extendMarkdownIt`, but how can I get the parsed tokens, or to parse the current document? 
Do you mean I can write a code using the `EnableSystemParser()` on the source code, and the repo has no API to parse or get tokens? 

Thanks for your kind help.

**Comment by manuth** [comment]
Using the `extendMarkdownIt`-method, you could store a copy of vscode's `markdown-it` instance.
That's what I do for MarkdownConverter:
https://github.com/manuth/MarkdownConverter/blob/2aa12a86c3863851da27676a9d14a6da32852cd2/src/System/Extensibility/Extension.ts#L110-L118

You could either copy my `Extension` class and get a copy of VSCode's `markdown-it` instance using a piece of code like this:
```ts
// Assuming `this` is the current `Extension` instance...

if (!this.VSCodeParser) {
    await EnableSystemParser();
}

let markdownIt = this.VSCodeParser;
```

Or you could write your own code which does something like this:
```
let markdownIt: MarkdownIt = null;

export = {
    extendMarkdownIt(md: any) {
        markdownIt = md;
    }
}
```
   1. Check whether `markdownIt` equals `null`
   2. If `markdownIt` equals `null`, do the following
       - Open up an empty, untitled Markdown file
       - Bring up the Markdown Preview using the `markdown.showPreview` command
       - Close both the Markdown Preview and the untitled Markdown file using the `workbench.action.closeActiveEditor` command
   3. `markdownIt` has been set now as `extendMarkdownIt` was triggered by `markdown.showPreview`
   4. Profit!

**Comment by yuis-ice** [comment]
umm okay, thanks for the detailed explanation. May I know in what part in the source code the vscode-compatible .render is available? So I can inspect the feature on a breakpoint while the debug launch on vscode.

**Comment by manuth** [comment]
If you're looking the place where `markdown-it`'s `.render` method is being invoked, it's here:
https://github.com/manuth/MarkdownConverter/blob/2aa12a86c3863851da27676a9d14a6da32852cd2/src/System/Documents/MarkdownFragment.ts#L26-L29

Though, you might want to enable `markdownConverter.Parser.SystemParserEnabled` in your settings in order to have VSCode's internal parser loaded.

The method you might be looking for might be `.parse` rather than `.render`, though.

**Comment by yuis-ice** [comment]
Thanks, I understand. Thanks for all of your kind help.

**Comment by manuth** [comment]
You're welcome, I'm glad I could help!
Best success to you
