### ISSUE TITLE
Convert to pdf does not work in subfolders

### ISSUE THREAD

**Issue by mjwsteenbergen** [manuth/MarkdownConverter#20]
Hey! Congrats on the new release! Its working great so far for me!

However, I stumbled onto a bug while using the extension. If I open folder "A", and have a document in "A\B\C.md" then it will print an empty document in "A\C.pdf". If I then open vscode in "B" and then convert "C.md", then it will convert just fine.

I think the problem might be [here](https://github.com/manuth/MarkdownConverter/blob/master/src/MarkdownConverter/ConvertCommand.ts#L281), where it is expected that the root of the document is the root of the workspace.

**Comment by manuth** [comment]
Hi Martijn
Thank you so much and also thanks for the contribution to this version!
I'll have a look at it asap. Sadly I'm currently working on another project so it might take some days until I can have a look at it.

About the `documentRoot` variable:
Perhaps I have mistaking with the name of the variable - I rather should have called it `webRoot` since it indicates what directory to host using `http-server`.
So setting this variable to `workspace.uri.fspath` is required in order to include pictures and stuff from relative paths inside the workspace.

**Comment by manuth** [comment]
Hello Martijn
Thanks for being patient!
I could reproduce the error and found the problem's root here:
https://github.com/manuth/MarkdownConverter/blob/1a3af1c57c9e6f1605c23a9cd00bd958d128d4d5/src/MarkdownConverter/Converter.ts#L86-L101

It's because  the url-variable doesn't contain the actual url but a windows-flavored relative path from the document-root to the document, which obviously uses `\\` as path-separator.

This causes the `if (request.url().endsWith(url + ".html"))`-branch to never apply which means that the hook won't be executed.

I could either change it back to `page.once` because the initial request is **always** the actual request for the document.  
The other option is to store the fully resolved url in the `url` variable and to compare it against `request.url()`.

Option A:
Option A would be to revert this portion of code to an older version which would look like this:
https://github.com/manuth/MarkdownConverter/blob/78a58698343fd119c95d7f566d4e2c74ea1f8eda/src/Converter.ts#L84-L93

Option B:
```ts
                let url = URL.resolve(
                    "http://localhost:8980/",
                    (this.Document.FileName ? Path.relative(this.DocumentRoot, this.Document.FileName) : "") + ".html");

                page.setRequestInterception(true);
                page.on(
                    "request",
                    request =>
                    {
                        if (request.url() === url)
                        {
                            request.respond({
                                body: htmlCode
                            });
                        } else
                        {
                            request.continue();
                        }
                    });

                await page.goto(url, { waitUntil: "networkidle0", timeout: 0 });
```

Personally I'd prefer option A.  
What do you think?

**Comment by mjwsteenbergen** [comment]
Thank you for your time! Don't worry if you want to do other things first, I can easily circumvent this issue, by just opening the folder.

I think A is also better. Even though B might be better for debugging, A is simpler and therefore less likely to have bugs and I think that is more important ;)

**Comment by manuth** [comment]
Yeah you're right, it might be very good for debugging.  
And I'd have to do less changes.

I'll just mess around with the settings for a little before I release a next version.
