### ISSUE TITLE
converted pdf file doesn't exist

### ISSUE THREAD

**Issue by jkhsjdhjs** [manuth/MarkdownConverter#22]
When having a folder open and an unrelated markdown document it tries to save the PDF document to the open folder.
![](https://screens.totally.rip/2018/10/5bcbaec9bd4c6.png)

`a2dp_sink` is the folder opened currently. `solr-for-openaas.md` is the file I opened from a different folder. In my opinion it would be better to save the created PDF file to the source folder of the markdown document by default.

Now to the main issue:
The file MarkdownConverter is showing on the screenshot doesn't exist.

When clicking on `Open File`:
![](https://screens.totally.rip/2018/10/5bcbafacac448.png)

I also checked the folder where the markdown file is located, no PDF there either.

**Comment by manuth** [comment]
Whether or not to store `MarkdownConverter`s output relative to the actual file or the workspace is pretty subjective which is the reason why I decided to leave the decision to the user to specify the location themselves.

Personally I prefer to store the output in a single directory which is why I decided to set `DestinationOrigin` to `WorkspaceRoot` by default.

I'll consider changing this to `DocumentFile` in a later version.

**Comment by jkhsjdhjs** [comment]
Thanks for the quick fix! I just tested it and it now tries to save the PDF to the source directory. However, the file still isn't created after conversion. Neither is it when I close the open folder and only have said document open.
I just noticed it also shows "This feature is not supported by your platform!" After clicking on `Open File`. However, I think this is most likely not related to the issue with the PDF file not being created.

**Comment by manuth** [comment]
Sadly I cannot reproduce this error on my Windows 10 machine.

At time of writing I've implemented the `Open File` feature only for `linux`-platforms, `macOS` and `Windows`. Sounds like you're using neither of them.

Showing up an error message is a pretty dirty fix tbh - I think I'll just hide the `Open File`-button if the platform isn't one of the supported ones.

What platform do you use?  
I think I'll need to set up some virtual machine in order to do some testing.

**Comment by jkhsjdhjs** [comment]
I'm actually using linux, Arch Linux 4.18.13-arch1-1-ARCH with KDE.

Is it possible that it just shows `This feature is not supported by your platform!` because it fails to open the file cause it doesn't exist?

**Comment by manuth** [comment]
Honestly I didn't set up any log-calls in my extension which means that one only can see what's going on by cloning the source and debugging it themself.

The project is completely written in `TypeScript` which is similar to `C#` or `Java`.
So if you have some basic knowledge of these languages you could give it a try to debug the extension.

**Comment by manuth** [comment]
Oh yeah
I totally forgot to mention the message definitely doesn't show up cause of an error:
https://github.com/manuth/MarkdownConverter/blob/13bd00e677aad06ff22c7fe6f6cba4fca9cfdbc2/src/MarkdownConverter/ConvertCommand.ts#L371-L383

It's a simple "switch-case" block.

**Comment by manuth** [comment]
I just recognized what's causing the message popping up...
I missed to add a `break;` after the linux-section.

The file not being created still is a riddle to me...
It's working on my Ubuntu 18.04.1 machine that I've just created.
