### ISSUE TITLE
Embedded style instead of links

### ISSUE THREAD

**Issue by badchenn** [manuth/MarkdownConverter#4]
I've used the configuration to include 2 css files.

		"style": {
			"useSystemStyles": false,
			"wrapper": "<div class=\"container\">\n{{ content }}\n</div>",
			"styleSheets": [
				"css/bootstrap.css",
				"css/style.css"
			]
		}

While the converted page works, it contains the full content of the 2 files - _instead_ of adding them as links.
You can imagine the advantage of linking to css files rather than including the css at that moment in time.
Is there a mechanism to allow links in lieu of inline css?

**Comment by manuth** [comment]
Hello badchenn
The content of local css-files is going to be inserted each time you convert your Markdown-file.
I decided to do it like that since my inspiration-repo handled it the same way.

I will try out if relative paths or "file://"-links are supported by PhantomJS and if they are I will update the extension.

Please be patient. I will be able to do that in 2 weeks - currently I'm writing my final thesis.

**Comment by Leedehai** [comment]
I don't feel like separating the css file and the html, however, because exporting a single file (the html file) from markdown looks more neat.
If I share my exported file to a person who doesn't know about CSS, he would not understand the existence of a css file and may probably ignore to download it, unless i explain it to him.

**Comment by manuth** [comment]
Oh fair - perhaps it's been made exactly for that reason...
I should add an option for it in the configuration's style-section.

**Comment by manuth** [comment]
You can now set what stylesheets to include (`All`, `Local`, `Web` or `None`, true or false) using the newly added `embeddingStyle`-setting:

```json
{
  "markdownConverter.document": {
    "style": {
      "embeddingStyle": "None"
  }
}
```
