### ISSUE TITLE
command 'markdownConverter.Convert' not found

### ISSUE THREAD

**Issue by mjwsteenbergen** [manuth/MarkdownConverter#41]
Hey,
It's great that you're still adding new features! Love the new progress bar when converting documents.

Today I tried to convert a markdown document and got the error: 
`command 'markdownConverter.Convert' not found`

I reinstalled the extension, but that also didnt help. Is this problem on my side?

**Comment by manuth** [comment]
Hi @mjwsteenbergen
This behavior is not to be expected.
The most recent version v3.0.0 is the very first version that has been built and published automatically by my CI server. Maybe something went wrong during the build process.

Please install the previous version v2.0.2 until I this issue is solved.

**Comment by manuth** [comment]
Okay It's my bad - looks like shelljs is not browserifiable which is why my extension caused errors.
I'm going to patch this by dropping shelljs from the dependency-list

stay tuned

**Comment by mjwsteenbergen** [comment]
Wow. Dude. That was fast! Nice work!

**Comment by manuth** [comment]
No problem.
I'll publish the new version in a few minutes.

**Comment by manuth** [comment]
Thank you, btw, for reporting the issue that rapidly!
This helps me a lot to improve the extension.
