### ISSUE TITLE
Double curly braces (angular template binding) cannot be used

### ISSUE THREAD

**Issue by capgeminiKoen** [manuth/MarkdownConverter#50]
I have problems when converting a document like this:

# Example doc
You can bind a variable to this template like this:
```HTML
<h1>{{title}}</h1>
```
Because - obviously - it is used by this awesome converter. The `{{title}}` part just disappears.
Any way around this atm?

Thanks in advance!
Koen

**Comment by manuth** [comment]
Hello @capgeminiKoen
As your markdown-file is processed using `mustache.js` you can easily escape this piece of code using something like this:
```md
{{=<% %>=}}
# title
<%={{ }}=%>
```

However, please leave this issue open, because actually `mustache.js` additionally would support to escape curly braces using this pattern `\{{ title }}`, but as currently the file is converted to `html` first and then processed using `mustache.js`, this method won't work (because the markdown-parser automatically removes the backslash).

This is an incorrect behavior and I'll have to fix this as soon as I can.

Sadly I'm having quite a lot of stress lately cause I'm in the middle of a schooling-year. Though, please stay tuned, because I'll work on `MarkdownConverter` again as soon as I can!

Thanks for using MarkdownConverter 😄

**Comment by capgeminiKoen** [comment]
Hi @manuth,

Thanks for your quick reply! :)
You are obviously correct. Just wrapping the entire file in these statements fixes my problems now.
Looks a bit weird in the previes, but compiles just fine.

Thank you so much! If I have some time left, I might make a PR for myself, but I can imagine you have a certain way that you'd want to solve this problem ;)

All the best :)

**Comment by manuth** [comment]
Oh - no worries
It's nothing but swapping these two lines of code:
https://github.com/manuth/MarkdownConverter/blob/55b1593478e4ba7d7be41c636ae5a58a3235c6e8/MarkdownConverter/src/System/Documents/Document.ts#L377-L378

There are several other thing I'd like to change for the next version of `MarkdownConverter` which is why I won't be able to publish a new version until I have some time left for coding.

If you are used to nodejs and npm you could also create your own installable `.vsix` file by invoking `npx vsce pack` after `npm install`ing this project locally.

Thanks for being patient.
