### ISSUE TITLE
Query About Network Access During PDF Conversion

### ISSUE THREAD

**Issue by GGillan** [manuth/MarkdownConverter#59]
Hi,

We had a very lengthy Internet outage here yesterday. During that time, I made a Markdown document and ran MarkdownConverter because I needed a PDF. The HTML conversion went fine, but the PDF conversion failed with a message approximating "unable to find URL". Until then I didn't realize that MarkdownConverter used any off-machine access during conversions.

Could you tell me what it uses Internet access for? Does the content of the document get sent outside of the local PC at any time?

Thanks!

**Comment by manuth** [comment]
@GGillan I'm terribly sorry, I almost forgot to answer your question.
The short answer to your question is no. Of course, the MarkdownConverter doesn't send data to any other PC, neither does it use any off-machine access during conversions.

If you're wondering what the MarkdownConverter accesses URLs for, I can dive a little more into detail for you.
I noticed, that Google Chrome doesn't load JavaScript files properly when opening html-files directly from the local machine (aka. `file://`-urls), due to some CORS-issues, iirc. For the conversion to PDF, self-contained HTML-files and pictures (such as png or jpeg) a local Chromium-installation is used. For that reason a local web-server is running during each conversion (bound to a random port on `localhost`).

### Important Code-Snippets
For better understanding I'll provide you the most important pieces of code in `MarkdownConverter`.

Here is the code that initializes the web-server during each conversion:
https://github.com/manuth/MarkdownConverter/blob/a1824643e41863ad5e7820dca75fa1f11c4b8182/src/Conversion/Converter.ts#L172-L211

For preparing the document to be converted to PDF, PNG or JPEG, a local chromium-instance is launched using `puppeteer-core`:
https://github.com/manuth/MarkdownConverter/blob/a1824643e41863ad5e7820dca75fa1f11c4b8182/src/Conversion/Converter.ts#L213
https://github.com/manuth/MarkdownConverter/blob/a1824643e41863ad5e7820dca75fa1f11c4b8182/src/Conversion/Converter.ts#L220-L240

The web-server is started before each conversion and closed after each conversion:
https://github.com/manuth/MarkdownConverter/blob/a1824643e41863ad5e7820dca75fa1f11c4b8182/src/System/Tasks/ConversionRunner.ts#L161
https://github.com/manuth/MarkdownConverter/blob/a1824643e41863ad5e7820dca75fa1f11c4b8182/src/System/Tasks/ConversionRunner.ts#L204

**Comment by manuth** [comment]
I hope I could clear up the reason for URL-access to you. Feel free to reopen this issue if you have any further questions.

Thank you very much for using MarkdownConverter
