### ISSUE TITLE
Images in .md files are causing an error when try to convert to HTML

### ISSUE THREAD

**Issue by amhayslip** [manuth/MarkdownConverter#66]
![Screen Shot 2021-02-25 at 3 30 13 PM](https://user-images.githubusercontent.com/5480326/109213251-5fb1bb00-777e-11eb-97df-220cacb6af6f.png)

**Comment by manuth** [comment]
Hello @amhayslip 
Sorry for letting you wait

This error is caused by the feature for hot-reloading pictures in the markdown-editor.
I have a workaround ready and on top of that, a PR was created for fixing this issue in vscode:
https://github.com/microsoft/vscode/pull/117041

This fix is included in vscode-insiders. Sadly I'm not actively working on MarkdownConverter at this very moment so you might want to switch to vscode-insiders until vscode v1.54 comes out.

**Comment by RoneoOrg** [comment]
I confirm: this is fixed with code-insiders 1.54.0

thank you

**Comment by amhayslip** [comment]
Awesome, thanks!
