### ISSUE TITLE
Conversion Fails with YAML warning

### ISSUE THREAD

**Issue by edward-agarwala** [manuth/MarkdownConverter#7]
Error: The YAML-block is malformatted. Line {0}, column {1}.

**Comment by manuth** [comment]
Hello Edward
YAML-Headers are currently required.
YAML-Headers must be placed on the very top of the file and must be formatted like this:
```
---
title: 'Hello World'
SomeMoreProperties: 'Value'
CreationDate: 2017-02-03
---
{Markdown-Content}
```

Sadly I cannot change this behaviour for the next week since I'm really very busy.
I'll fix this in the next version. Please stay patient.

Thanks for using MarkdownConverter

~Manu

**Comment by manuth** [comment]
I sadly couldn't reproduce the error.
Can you please send me the markdown-file you're trying to convert?

~Manu

**Comment by manuth** [comment]
Hello, edward

Recent events revealed that this error occurs cause of platform compatibility issues.
Are you using a macOS-computer?
I'll try to work it out during the next few days.

**Comment by edward-agarwala** [comment]
```
# Meeting
Atendees

    - me

## Topic 1
```
I am on mac OS 10.11.6.

**Comment by edward-agarwala** [comment]
```
---
title: 'Hello World'
SomeMoreProperties: 'Value'
CreationDate: 2017-02-03
---
# Meeting
Atendees

    - me

## Topic 1
```
Also produces the same error.

**Comment by manuth** [comment]
Hey edward
In this case it's the `front-matter` module not working correctly on macOS.
Sadly I don't have access to a macOS-machine so it may take some time to fix this issue.

Please stay patient

**Comment by manuth** [comment]
Hello - I could finally find the source of the problem!
Honestly I mixed up the IDs of the YAMLException message and the PhantomJSRebuildException message, so that's why you've got such confusing messages.

Since you're _always_ getting this error I assume PhantomJS cannot be rebuilt cause of SSL certification-errors or something like that.

I, for example, cannot rebuild PhantomJS in my company's network for some reason I don't know.
I'll fix the error-messages.

I honestly don't know how to handle the error during the rebuilding of phantomjs. I could include a prebuilt version of phantomjs for each platform but you see - that would blow my project pretty much s:
