### ISSUE TITLE
Probs rendering images from local filesystem

### ISSUE THREAD

**Issue by urban-thinking** [manuth/MarkdownConverter#9]
Hi,

when I try to use an image from local filesystem it's shown in preview of VS Code but not rendered in final .pdf file.

Sample Markdown code:

`![alt](file:///Users/ep/Desktop/image.png)
`
or

`![alt](/Users/ep/Desktop/image.png)`

Both are shown correctly in Code preview.

kind regards
Emilio

**Comment by manuth** [comment]
Hello @urban-thinking 
It took me a lil research to find out file:, javascript: and data:-links are disabled in `markdown-it` by default.
The only thing I had to do was to disable the link-policy.
It's working just fine now!
It will be fixed in the next commit.

Sadly PhantomJS doesn't support relative paths yet (https://github.com/ariya/phantomjs/issues/10610) but absolute paths are working fine.

**Comment by manuth** [comment]
Guys - I've got a great idea on how to enable relative paths even if phantomjs' behaviour is very weird:
MarkdownConverter will open up a small webserver temporary and phantomjs will load the webpage from there.
This will solve all relative path issues, I guess...

Stay tuned - this will be implemented in the next version...
It'll take some time because I'm also working on a Resource-Manager to load localized files/strings

**Comment by urban-thinking** [comment]
Hmm, this idea is as great as it is simple. In shell I go to (above sample) /Users/ep/Desktop/, there I start the PHP built in WebServer with:

>php -S localhost:8000

Now I can reference the image in MD with:

![alt](http://localhost:8000/image.png)

Problem solved. At least ... for me :-D

Thank you.

**Comment by manuth** [comment]
Awesome!
This confirms my guess. I'll implement it as soon as I can. Sadly this may take a while since I'm currently working on something else...

**Comment by manuth** [comment]
@urban-thinking I hope it hasn't been too long.
I finally managed it to work out some dirty fix for this.

MarkdownConverter will now serve a website using [`http-server`](https://www.npmjs.com/package/http-server) each time when a PDF or an image-file is generated.

This allows you to include pictures etc. from the local file-system.
I'll continue working on this. This definitely will be implemented in the next version.

Stay tuned!
Thanks for using MarkdownConverter

**Comment by manuth** [comment]
@urban-thinking

You may have noticed it already: the new major release of MarkdownConverter is out since yesterday.
The enhancement you've recommended is included in this version so just go and grab it!

Thank you for your suggestion :smile:
